enum
{
    THREAD_LOOKUP_BANS,
    THREAD_LOOKUP_ACCOUNT,
    THREAD_ACCOUNT_REGISTER,
    THREAD_PROCESS_LOGIN,
    THREAD_COUNT_FLAGS,
    THREAD_TRACE_IP,
    THREAD_LIST_HELPERS,
    THREAD_LOAD_HOUSES,
    THREAD_LIST_TENANTS,
    THREAD_LOAD_FURNITURE,
    THREAD_LOAD_GARAGES,
    THREAD_LOAD_BUSINESSES,
    THREAD_LOAD_ENTRANCES,
    THREAD_LOAD_CLOTHING,
    THREAD_LOAD_FACTIONS,
    THREAD_LOAD_FACTIONRANKS,
    THREAD_LOAD_FACTIONSKINS,
    THREAD_LOAD_FACTIONPAY,
    THREAD_LOAD_DIVISIONS,
    THREAD_LOAD_LANDS,
    THREAD_LOAD_LANDOBJECTS,
    THREAD_LOAD_GANGS,
    THREAD_LOAD_GANGRANKS,
    THREAD_LOAD_GANGSKINS,
    THREAD_LOAD_POINTS,
    THREAD_LOAD_TURFS,
    THREAD_HOUSE_INFORMATION,
    THREAD_COUNT_FURNITURE,
    THREAD_SELL_FURNITURE,
    THREAD_CLEAR_FURNITURE,
    THREAD_COUNT_TEXTS,
    THREAD_VIEW_TEXTS,
    THREAD_LIST_VEHICLES,
    THREAD_FACTION_ROSTER,
    THREAD_GANG_ROSTER,
    THREAD_VIEW_PHONEBOOK,
    THREAD_COUNT_LANDOBJECTS,
    THREAD_SELL_LANDOBJECT,
    THREAD_DUPLICATE_LANDOBJECT,
    THREAD_DUPLICATED_OBJECT,
    THREAD_CLEAR_LANDOBJECTS,
    THREAD_LIST_LANDOBJECTS,
    THREAD_LAND_INFORMATION,
    THREAD_LOAD_VEHICLES,
    THREAD_GANG_INFORMATION,
    THREAD_OFFLINE_IP,
    THREAD_CHECK_REFERRAL,
    THREAD_REWARD_REFERRER,
    THREAD_LIST_FLAGGED,
    THREAD_CAR_STORAGE,
	THREAD_DMVRELEASE,
    THREAD_LAND_MAINMENU,
    THREAD_LIST_ADMINS,
	THREAD_LOAD_ACTORS
};

enum
{
	DIALOG_REGISTER = 1,
	DIALOG_CONFIRMPASS,
	DIALOG_CARSTORAGE,
	DIALOG_LOGIN,
	DIALOG_GENDER,
	DIALOG_AGE,
	DIALOG_REFERRAL,
	DIALOG_INTERIORS,
	DIALOG_BUYFURNITURE1,
	DIALOG_VERIFICATION,
	DIALOG_VERIFICATION1,
	LotteryNumber,
	GatePass,
	DIALOG_BUYFURNITURE2,
	DIALOG_GRAFFITICOLOR,
	DIALOG_GRAFFITITEXT,
	DIALOG_BUY,
	DIALOG_BUYOUTSIDE,
	DIALOG_EDITBUY,
	DIALOG_EDITBUY2,
	DIALOG_BUYCLOTHES,
	DIALOG_PICKLOAD,
	DIALOG_UNREADTEXTS,
	DIALOG_ATM,

	DIALOG_STEAL,
	Loot_Weapon,
	DIALOG_MENU_WC,
	
	DIALOG_CHANGEPASS,
	DIALOG_BUYCLOTHINGTYPE,
	DIALOG_BUYCLOTHING,
	DIALOG_CLOTHING,
	DIALOG_CLOTHINGMENU,
	DIALOG_CLOTHINGEDIT,
	DIALOG_CLOTHINGBONE,
	DIALOG_BUYVEHICLE,
	DIALOG_BUYVEHICLE2,
 	DIALOG_BUYBOAT,
	DIALOG_BUYAIRCRAFT,
	DIALOG_SPAWNCAR,
    DIALOG_DESPAWNCAR,
    DIALOG_FINDCAR,
	DIALOG_BIZINTERIOR,
	DIALOG_FACTIONLOCKER,
	DIALOG_FACTIONEQUIPMENT,
	DIALOG_FACTIONSKINS,
	DIALOG_HITMANCLOTHES,
	DIALOG_MDC,
	DIALOG_MDCWANTED,
	DIALOG_MDCPLAYER1,
	DIALOG_MDCPLAYER2,
	DIALOG_MDCCHARGES,
	DIALOG_PLAYERLOOKUP,
	DIALOG_VEHICLELOOKUP1,
 	DIALOG_VEHICLELOOKUP2,
 	DIALOG_FACTIONPAY1,
 	DIALOG_FACTIONPAY2,
 	DIALOG_PHONEBOOK,
 	DIALOG_CREATEZONE,
 	DIALOG_KIOSK,
 	DIALOG_REFUNDED,
 	DIALOG_PAWNSHOP,
 	DIALOG_CBUG,
 	DIALOG_CONFIRMZONE,
 	DIALOG_LANDBUILD1,
 	DIALOG_LANDBUILD2,
 	DIALOG_LANDBUILDTYPE,
 	DIALOG_LANDMENU,
 	DIALOG_LANDEDITOBJECT,
 	DIALOG_LANDOBJECTMENU,
 	DIALOG_LANDOBJECTS,
 	DIALOG_LANDSELLALL,
 	DIALOG_LANDPERMS,
 	DIALOG_MP3PLAYER,
 	DIALOG_MP3MUSIC,
 	DIALOG_MP3RADIO,
 	DIALOG_MP3URL,
 	DIALOG_MP3RADIOGENRES,
 	DIALOG_MP3RADIOSUBGENRES,
 	DIALOG_MP3RADIORESULTS,
 	DIALOG_MP3RADIOSEARCH,
 	DIALOG_USECOOKIES,
 	DIALOG_GCLOTHES,
 	DIALOG_GANGSTASH,
 	DIALOG_GANGSTASHWEAPONS1,
	DIALOG_GANGSTASHWEAPONS2,
	DIALOG_GANGSTASHDRUGS1,
	DIALOG_GANGSTASHDRUGS2,
	DIALOG_GANGSTASHAMMO1,
	DIALOG_GANGSTASHAMMO2,
	DIALOG_GANGSTASHMATS,
	DIALOG_GANGSTASHCASH,
 	DIALOG_GANGDEPOSIT,
 	DIALOG_GANGWITHDRAW,
 	DIALOG_GANGSKINS,
 	DIALOG_GANGFINDCAR,
 	DIALOG_GANGPOINTSHOP,
 	DIALOG_GANGARMSDEALER,
 	DIALOG_GANGARMSWEAPONS,
 	DIALOG_GANGARMSAMMO,
 	DIALOG_GANGAMMOBUY,
 	DIALOG_GANGARMSEDIT,
 	DIALOG_GANGARMSPRICES,
 	DIALOG_GANGARMSPRICE,
 	DIALOG_GANGARMSDEPOSITMATS,
	DIALOG_GANGARMSWITHDRAWMATS,
	DIALOG_GANGAMMODEPOSITS,
	DIALOG_GANGAMMODEPOSIT,
	DIALOG_GANGAMMOWITHDRAWS,
	DIALOG_GANGAMMOWITHDRAW,
	DIALOG_GANGDRUGDEALER,
	DIALOG_GANGDRUGSHOP,
	DIALOG_GANGDRUGEDIT,
	DIALOG_GANGDRUGPRICES,
	DIALOG_GANGDRUGPRICE,
	DIALOG_GANGDRUGBUY,
	DIALOG_GANGDRUGDEPOSITS,
	DIALOG_GANGDRUGDEPOSIT,
	DIALOG_GANGDRUGWITHDRAWS,
	DIALOG_GANGDRUGWITHDRAW,
	DIALOG_REMOVEPVEH,
	DIALOG_FREENAMECHANGE,
 	DIALOG_BIZMENU,
	DIALOG_BIZNAME,
	DIALOG_BIZFEE,
	DIALOG_BIZSAFE,
	DIALOG_WITHDRAW,
	DIALOG_DEPOSIT,
	DIALOG_MESSAGE,
	DIALOG_BIZLOCK,
	DIALOG_POINTLIST,
	DIALOG_TURFLIST,
	DIALOG_PAYCHECK,
	DIALOG_TOP,
	DIALOG_RULES,
	DIALOG_PAINTBALL,
	DIALOG_CREATEQUIZ,
	DIALOG_BLACKMARKET1,
	DIALOG_CONVERSION,
	DIALOG_CONVERSION1,
	DIALOG_CONVERSION2,
	DIALOG_CONVERSION3,
	DIALOG_JOBINFO,
	DIALOG_BUTCHER,
	DIALOG_FREEBIES,

	// Sabong
	ShowCockFightMenu,
	ShowSetFighterMenu1,
	ShowSetFighterMenu2,
	ShowFightTypeSelection,
	ShowChargeMenu,

	// Billboards
	BillboardList,
	BillboardRent,
	BillboardRent2,
	BillboardRentFinal,
	BillboardCreate,
	MyBillboards,

	// Graffiti
	GraffityList,
	Graffity_CE,
	Graffity_CE_Done,
	Graffity_CE_Cancel,
	Graffity_CE_Text,
	Graffity_CE_Color,
	Graffity_CE_BackColor,
	Graffity_CE_Font,
	Graffity_CE_FontSize,

	// Anticheat
	ANTICHEAT_SETTINGS,
	ANTICHEAT_EDIT_CODE,

	// Trucker
	DIALOG_LOADTRUCK,
	DIALOG_LEGAL_LOADTRUCK,
	DIALOG_ILLEGAL_LOADTRUCK,

	// Corpse
	CorpseInfo,
	CorpseInfo2,

	// VIP
	DIALOG_VIPLOCKER,
	DIALOG_VIPLOCKER1,

	// Casino
	DIALOG_CASINO,
	DIALOG_CASINO2,
	DIALOG_CASINO3,

	// Voucher
	DIALOG_VOUCHER,
	DIALOG_NEXT_VOUCHER,
	DIALOG_CAR_VOUCHER,
	DIALOG_RARECAR_VOUCHER,
	DIALOG_RESTRICTEDCAR_VOUCHER,

	// Inventory
	DIALOG_INVPOT,
    DIALOG_INVGIVEPOT,
    DIALOG_INVGIVEPOT2,
    DIALOG_INVGIVEPOT3,
    DIALOG_INVSELLPOT,
    DIALOG_INVSELLPOT2,
    DIALOG_INVCRACK,
    DIALOG_INVGIVECRACK,
    DIALOG_INVGIVECRACK2,
    DIALOG_INVGIVECRACK3,
    DIALOG_INVSELLCRACK,
    DIALOG_INVSELLCRACK2,
    DIALOG_INVMETH,
    DIALOG_INVGIVEMETH,
    DIALOG_INVGIVEMETH2,
    DIALOG_INVGIVEMETH3,
    DIALOG_INVSELLMETH,
    DIALOG_INVSELLMETH2,
    DIALOG_INVPK,
    DIALOG_INVGIVEPK,
    DIALOG_INVGIVEPK2,
    DIALOG_INVGIVEPK3,
    DIALOG_INVSELLPK,
    DIALOG_INVSELLPK2,
    DIALOG_INVMATS,
    DIALOG_INVGIVEMATS,
    DIALOG_INVGIVEMATS2,
    DIALOG_INVGIVEMATS3,
    DIALOG_INVSELLMATS,
    DIALOG_INVSELLMATS2,
    DIALOG_INVFOOD,
    DIALOG_INVGIVEFOOD,
    DIALOG_INVGIVEFOOD2,
    DIALOG_INVGIVEFOOD3,
    DIALOG_INVSELLFOOD,
    DIALOG_INVSELLFOOD2,
    DIALOG_INVDRINK,
    DIALOG_INVGIVEDRINK,
    DIALOG_INVGIVEDRINK2,
    DIALOG_INVGIVEDRINK3,
    DIALOG_INVSELLDRINK,
    DIALOG_INVSELLDRINK2,
    DIALOG_INVRK,
    DIALOG_INVGIVERK,
    DIALOG_INVGIVERK2,
    DIALOG_INVGIVERK3,
    DIALOG_INVSELLRK,
    DIALOG_INVSELLRK2,

	// Phone
	DIALOG_PHONE_BUY,
	DIALOG_PHONE_GCASH,
	DIALOG_PHONE_GCASH2,
	DIALOG_PHONE_LOCATE,
	DIALOG_PHONE_SHARELOCATION,
	DIALOG_PHONE_SMS,
	DIALOG_PHONE_SMS2,
	DIALOG_PHONE_CALL,
	DIALOG_PHONE_ADS,
	DIALOG_PHONE_TWITTER,

	// Purge
	DIALOG_CONFIG_PURGE,
	DIALOG_SETUP_PURGE,

	// Backpack
	DIALOG_BP_MAIN,
	DIALOG_BP_CATEGORY,
	DIALOG_PUT_TAKE,

	// Vehicle Stash
	DIALOG_VEHSTASH_MAIN,
	DIALOG_VEHSTASH_CATEGORY,

	// House Stash
	DIALOG_HOUSE_STASH_MAIN,
	DIALOG_HOUSE_STASH_CATEGORY,
	DIALOG_HOUSE_STASH_PUT_TAKE,

	// Weapon License Exam
	DIALOG_WEP_TEST,
	DIALOG_WEP_QUESTION_1,
	DIALOG_WEP_QUESTION_2,
	DIALOG_WEP_QUESTION_3,
	DIALOG_WEP_QUESTION_4,
	DIALOG_WEP_QUESTION_5,
	DIALOG_WEP_QUESTION_6,
	DIALOG_WEP_QUESTION_7,
	DIALOG_WEP_QUESTION_8,

	// Binds
	mybinds,
	bindaction,
	bindedittype,
	bindeditmsg,

	// House Build
	DIALOG_HOUSEBUILD,
	DIALOG_BUYBUILD,

	// Phone
	DIALOG_BUY_PHONE,
	DIALOG_LOAD_PHONE,
	DIALOG_SIM_PHONE,
	DIALOG_MAIN_PHONE,
	DIALOG_PHONE_CASH,
	DIALOG_PHONE_LOCATION,
	DIALOG_PHONE_TWEETER,
	DIALOG_PHONE_FACEBOOK,
	DIALOG_PHONE_SEND_GCASH,

	// Other dialog	
	DIALOG_SPAWNPOINT,
	DIALOG_LOOT,
	DIALOG_VOICECHAT,
	DIALOG_EMOTE,
	DIALOG_INTERACT_MENU,
	DIALOG_INTERACT_PAY,
	DIALOG_INTERACT_GIVE,
	DIALOG_INTERACT_AMOUNT,
	DIALOG_VIPTOYS,
	DIALOG_SKIN_MENU,
	DIALOG_SKIN_LIST,
	DIALOG_VIP_CLOTHES,
	DIALOG_MEDICINE,
	DIALOG_FOOD_INVENTORY,
	DIALOG_STOCK_INVENTORY,
	DIALOG_VEHICLEMENU,
	DIALOG_PAYTICKET,
	DIALOG_DMVRELEASE,
	DIALOG_CRATE_BOX,
	DIALOG_LOCATE,
	DIALOG_LOCATE_LIST1,
	DIALOG_LOCATE_LIST2,
	DIALOG_LOCATE_LIST3,
	DIALOG_LOCATE_LIST4,
	DIALOG_GHELP,
	DIALOG_FHELP,
	DIALOG_STATS,
	DIALOG_STATS1,
	DIALOG_SETTINGS,
	DIALOG_INVSTATS,
	DIALOG_ADMINHELP,
	DIALOG_BETAINFO,
	DIALOG_NEWBIE,
	DIALOG_NEWBIEUNMUTE,
	DIALOG_NONE,
	DIALOG_CDBUY,
	DIALOG_NEXT_STATS,
	DIALOG_PREV_STATS,
	DIALOG_NEXT_INVENTORY,
	DIALOG_PREV_INVENTORY,
}

enum
{
	VEHICLE_ENGINE,
	VEHICLE_LIGHTS,
	VEHICLE_ALARM,
	VEHICLE_DOORS,
	VEHICLE_BONNET,
	VEHICLE_BOOT,
	VEHICLE_OBJECTIVE
};

enum
{
	STASH_CAPACITY_CASH,
	STASH_CAPACITY_MATERIALS,
	STASH_CAPACITY_WEED,
	STASH_CAPACITY_COCAINE,
	STASH_CAPACITY_METH,
 	STASH_CAPACITY_PAINKILLERS,
 	STASH_CAPACITY_HPAMMO,
	STASH_CAPACITY_POISONAMMO,
	STASH_CAPACITY_FMJAMMO,
	STASH_CAPACITY_WEAPONS
};

enum
{
 	E_OBJECT_TYPE,
	E_OBJECT_INDEX_ID,
	E_OBJECT_EXTRA_ID,
	E_OBJECT_3DTEXT_ID,
 	E_OBJECT_OPENED,
 	E_OBJECT_WEAPONID,
 	E_OBJECT_AMMO,
 	E_OBJECT_FACTION,
	E_OBJECT_GUN3DTEXT,
	E_OBJECT_EVENT,
 	E_OBJECT_X,
 	E_OBJECT_Y,
 	E_OBJECT_Z
};

enum
{
	E_OBJECT_FURNITURE,
	E_OBJECT_WEAPON,
	E_OBJECT_LAND
};

enum
{
	EDIT_FURNITURE_PREVIEW = 1,
	EDIT_OBJECT_PREVIEW,
	EDIT_FURNITURE,
	EDIT_CLOTHING_PREVIEW,
	EDIT_CLOTHING,
	EDIT_LAND_OBJECT_PREVIEW,
	EDIT_LAND_OBJECT,
	EDIT_LAND_GATE_MOVE,
	EDIT_VIPCLOTHING
};

enum
{
	DEPLOY_SPIKESTRIP,
	DEPLOY_CONE,
	DEPLOY_ROADBLOCK,
	DEPLOY_BARREL,
	DEPLOY_FLARE
};

enum
{
 	BUSINESS_STORE,
 	BUSINESS_GUNSHOP,
 	BUSINESS_CLOTHES,
 	BUSINESS_GYM,
 	BUSINESS_RESTAURANT,
 	BUSINESS_AGENCY,
 	BUSINESS_BARCLUB,
 	BUSINESS_PHARMACY,
	// Dealership
	BUSINESS_DEALERSHIP,
};

enum
{
	ILLEGAL_GUNS,
	ILLEGAL_DRUGS,
	ILLEGAL_MATS
};
enum
{
	FACTION_NONE,
	FACTION_POLICE,
	FACTION_MEDIC,
	FACTION_NEWS,
	FACTION_GOVERNMENT,
	FACTION_HITMAN,
	FACTION_FEDERAL,
	FACTION_MECHANIC,
	FACTION_CARTEL,
	FACTION_ARMY,
	FACTION_CHURCH,
	FACTION_INFINITEA,
	FACTION_TERRORIST,
	FACTION_GREENWICH
};

enum
{
	JOB_NONE = -1,
	JOB_PIZZAMAN,
	JOB_TRUCKER,
	JOB_FISHERMAN,
	JOB_BODYGUARD,
	JOB_ARMSDEALER,
	JOB_TAXIDRIVER,
	JOB_DRUGDEALER,
	JOB_LAWYER,
	JOB_DETECTIVE,
	JOB_MINER,
	JOB_BUTCHER,
	JOB_ADONIS,
	JOB_CONSTRUCTION,
	JOB_CRAFTSMAN,
	JOB_HARVESTER,
	JOB_GARBAGE,
	JOB_BRINKS,
	JOB_TAILOR,
	JOB_SWEEPER,
	JOB_GREENWICH,
};

enum
{
	CHECKPOINT_NONE = 0,
	CHECKPOINT_PIZZA,
	CHECKPOINT_TEST,
	CHECKPOINT_MATS,
	CHECKPOINT_DRUGS,
	CHECKPOINT_HOUSE,
	CHECKPOINT_MINING,
	CHECKPOINT_ROBBERY,
	CHECKPOINT_ROBBERYBIZ,
	CHECKPOINT_ROBBERYHOUSE,
	CHECKPOINT_TRUCKER,
	CHECKPOINT_LOADTRUCK,
	CHECKPOINT_MISC,
	CHECKPOINT_BUTCHER1,
	CHECKPOINT_BUTCHER2,
	CHECKPOINT_BUTCHER3,
	CHECKPOINT_CONSTRUCTION,
	CHECKPOINT_CONSTRUCTION2,
	CHECKPOINT_HARVEST,
	CHECKPOINT_GARBAGE,
	CHECKPOINT_LA_ROUTE,
	CHECKPOINT_LA_RETURN,
	CHECKPOINT_ENTERWOOL,
	CHECKPOINT_GETWOOL,
	CHECKPOINT_LOADWOOL,
	CHECKPOINT_DELIVERWOOL,
	CHECKPOINT_RETURNTAILOR,
	CHECKPOINT_GREENWICH
};

enum 
{
	VEHICLE_OFFSET_BOOT,
	VEHICLE_OFFSET_HOOD,
	VEHICLE_OFFSET_ROOF
};

enum
{
	HANGUP_DROPPED,
	HANGUP_USER
};

enum
{
	MUSIC_NONE,
	MUSIC_MP3PLAYER,
	MUSIC_BOOMBOX,
	MUSIC_VEHICLE
};

enum
{
	ITEM_WEAPON,
	ITEM_SELLGUN,
	ITEM_MATERIALS,
	ITEM_REPAIRKIT,
	ITEM_WEED,
	ITEM_COCAINE,
	ITEM_METH,
	ITEM_PAINKILLERS,
	ITEM_SEEDS,
	ITEM_EPHEDRINE,
	ITEM_CASH,
	ITEM_HPAMMO,
	ITEM_BACKPACK,
	ITEM_POISONAMMO,
	ITEM_FMJAMMO
};

enum
{
	CAPACITY_MATERIALS,
	CAPACITY_WEED,
	CAPACITY_COCAINE,
	CAPACITY_METH,
	CAPACITY_PAINKILLERS,
	CAPACITY_SEEDS,
	CAPACITY_EPHEDRINE,
 	CAPACITY_HPAMMO,
	CAPACITY_POISONAMMO,
	CAPACITY_FMJAMMO
};

enum
{
	LIMIT_HOUSES,
	LIMIT_BUSINESSES,
	LIMIT_GARAGES,
	LIMIT_VEHICLES
};

enum
{
	POINT_DRUGFACTORY = 1,
	POINT_DRUGDEN,
	POINT_CRACKHOUSE,
	POINT_AUTOEXPORT,
	POINT_FUEL,
	POINT_MATPICKUP1,
	POINT_MATPICKUP2,
	POINT_MATFACTORY1,
	POINT_MATFACTORY2
};

enum
{
	GANGWEAPON_9MM,
	GANGWEAPON_SDPISTOL,
	GANGWEAPON_DEAGLE,
	GANGWEAPON_SHOTGUN,
	GANGWEAPON_SPAS12,
	GANGWEAPON_SAWNOFF,
	GANGWEAPON_TEC9,
	GANGWEAPON_UZI,
	GANGWEAPON_MP5,
	GANGWEAPON_AK47,
	GANGWEAPON_M4,
	GANGWEAPON_RIFLE,
	GANGWEAPON_SNIPER,
	GANGWEAPON_MOLOTOV
};

enum
{
	TAG_NORMAL,
	TAG_ADMIN,
	TAG_HELPER
};

enum
{
	AMMO_HP,
	AMMO_POISON,
	AMMO_FMJ
};

enum
{
	AMMOTYPE_NORMAL,
	AMMOTYPE_HP,
	AMMOTYPE_POISON,
	AMMOTYPE_FMJ
};

enum
{
	ZONETYPE_LAND = 1,
	ZONETYPE_TURF,
	ZONETYPE_SAFEZONE
};

enum
{
	HOSPITAL_COUNTY = 1,
	HOSPITAL_ALLSAINTS = 0
};

enum
{
	SKILL_PISTOL = 0,
	SKILL_UZI,
	SKILL_SAWNOFF
};

enum 
{
	ROB_RESET,
	ROB_BANK,
	ROB_STORE,
	ROB_HOUSE
};

enum
{
	GENDER_MALE = 1,
	GENDER_FEMALE
};

enum SAZONE_MAIN { //Betamaster
	SAZONE_NAME[28],
	Float:SAZONE_AREA[6]
};