name: Compile SA-MP GameMode

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Notify Discord Status
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"embeds": [{"title": "[server] compile success on main", "color": 3066993}]}' \
          "https://discord.com/api/webhooks/1548723118527357019/HEnSmXMg1Itjird0M7NmQVaRd8RnHrqZvbGNEtx8ih2l50oVsXZZprAbDo9wN7DKegxt"